kind: pipeline
name: default

# build image
steps:
  - name: build
    image: ubuntu:latest
    commands:
      - apt update -y
      - apt install build-essential wget unzip ansible openssh-client -y
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - wget https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip
      - unzip packer_1.6.6_linux_amd64.zip
      - mv packer /usr/bin
      - make
      - make copy2ssm
    environment: 
      PKR_VAR_aws_access_key:
        from_secret: PKR_VAR_aws_access_key
      PKR_VAR_aws_secret_key: 
        from_secret: PKR_VAR_aws_secret_key
      AWS_ACCESS_KEY_ID:
        from_secret: PKR_VAR_aws_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: PKR_VAR_aws_access_key
    when:
      branch:
       - main
    trigger:
      event:
      - push
