kind: pipeline
name: build_image

# build image
steps:
  - name: build
    image: appleboy/drone-packer
    environment: 
      PKR_VAR_aws_access_key:
        from_secret: PKR_VAR_aws_access_key
      PKR_VAR_aws_secret_key: 
        from_secret: PKR_VAR_aws_secret_key
    template: ubuntu.pkr.hcl
    actions:
    - validate
    - build
    when:
      branch:
       - main
    trigger:
      event:
      - push
